In [2]:
import pandas as pd
import numpy as np
import os

In [21]:
# iterate over all files in data/title_pairs, save dataframes in a dictionary
title_pairs = {}
for file in os.listdir('../data/title_pairs'):
    title_pairs[file] = pd.read_csv(f'../data/title_pairs/{file}')

In [22]:
# print current path
title_pairs.keys()

dict_keys(['karrierewege_plus_occ_train_pairs.csv', 'decorte_val_pairs.csv', 'karrierewege_plus_cp_train_pairs.csv', 'karrierewege_plus_occ_val_pairs.csv', 'karrierewege_plus_occ_test_pairs.csv', 'karrierewege_plus_cp_test_pairs.csv', 'decorte_test_pairs.csv', 'talent_clef_pairs.csv', 'karrierewege_plus_cp_val_pairs.csv', 'decorte_train_pairs.csv'])

In [23]:
# print column names of the dataframes
for key in title_pairs.keys():
    print(key)
    print(title_pairs[key].columns)
    print("--------------------------------")

karrierewege_plus_occ_train_pairs.csv
Index(['raw_title', 'esco_title', 'esco_id'], dtype='object')
--------------------------------
decorte_val_pairs.csv
Index(['raw_title', 'esco_title', 'esco_id'], dtype='object')
--------------------------------
karrierewege_plus_cp_train_pairs.csv
Index(['raw_title', 'esco_title', 'esco_id'], dtype='object')
--------------------------------
karrierewege_plus_occ_val_pairs.csv
Index(['raw_title', 'esco_title', 'esco_id'], dtype='object')
--------------------------------
karrierewege_plus_occ_test_pairs.csv
Index(['raw_title', 'esco_title', 'esco_id'], dtype='object')
--------------------------------
karrierewege_plus_cp_test_pairs.csv
Index(['raw_title', 'esco_title', 'esco_id'], dtype='object')
--------------------------------
decorte_test_pairs.csv
Index(['raw_title', 'esco_title', 'esco_id'], dtype='object')
--------------------------------
talent_clef_pairs.csv
Index(['esco_id', 'raw_title'], dtype='object')
--------------------------------
karrierewege_plus_cp_val_pairs.csv
Index(['raw_title', 'esco_title', 'esco_id'], dtype='object')
--------------------------------
decorte_train_pairs.csv
Index(['raw_title', 'esco_title', 'esco_id'], dtype='object')
--------------------------------

In [26]:
# concat all dataframes in title_pairs, add column with filename = key
for key in title_pairs.keys():
    title_pairs[key]['filename'] = key

all_pairs = pd.concat(title_pairs.values(), ignore_index=True)

In [28]:
pool = pd.read_csv('../data/occupations_en.csv')
all_pairs = all_pairs.merge(pool[['conceptUri', 'preferredLabel']], left_on='esco_id', right_on='conceptUri', how='left')
all_pairs.head()

,raw_title,esco_title,esco_id,filename,conceptUri,preferredLabel
0,Interface Developer,integration engineer,http://data.europa.eu/esco/occupation/07e60525...,karrierewege_plus_occ_train_pairs.csv,http://data.europa.eu/esco/occupation/07e60525...,integration engineer
1,Railroad Development Engineer,rail project engineer,http://data.europa.eu/esco/occupation/3f3748a7...,karrierewege_plus_occ_train_pairs.csv,http://data.europa.eu/esco/occupation/3f3748a7...,rail project engineer
2,Public Safety Investigator,police inspector,http://data.europa.eu/esco/occupation/ce2b8609...,karrierewege_plus_occ_train_pairs.csv,http://data.europa.eu/esco/occupation/ce2b8609...,police inspector
3,AI Systems Developer,artificial intelligence engineer,http://data.europa.eu/esco/occupation/35553663...,karrierewege_plus_occ_train_pairs.csv,http://data.europa.eu/esco/occupation/35553663...,artificial intelligence engineer
4,In-Home Care Provider,residential home adult care worker,http://data.europa.eu/esco/occupation/78f474ae...,karrierewege_plus_occ_train_pairs.csv,http://data.europa.eu/esco/occupation/78f474ae...,residential home adult care worker

In [29]:
# check conceptUri coverage by filename
coverage = all_pairs.groupby('filename')['conceptUri'].apply(lambda x: (x.notna().sum() / len(x)) * 100)
print("Coverage of conceptUri by filename (%):")
print(coverage)

Coverage of conceptUri by filename (%):
filename
decorte_test_pairs.csv                    99.892009
decorte_train_pairs.csv                   99.983774
decorte_val_pairs.csv                    100.000000
karrierewege_plus_cp_test_pairs.csv      100.000000
karrierewege_plus_cp_train_pairs.csv     100.000000
karrierewege_plus_cp_val_pairs.csv       100.000000
karrierewege_plus_occ_test_pairs.csv     100.000000
karrierewege_plus_occ_train_pairs.csv    100.000000
karrierewege_plus_occ_val_pairs.csv      100.000000
talent_clef_pairs.csv                    100.000000
Name: conceptUri, dtype: float64

In [31]:
all_pairs.groupby('filename').count()

,raw_title,esco_title,esco_id,conceptUri,preferredLabel
filename,,,,,
decorte_test_pairs.csv,926,926,926,925,925
decorte_train_pairs.csv,6163,6163,6163,6162,6162
decorte_val_pairs.csv,841,841,841,841,841
karrierewege_plus_cp_test_pairs.csv,14953,14953,14953,14953,14953
karrierewege_plus_cp_train_pairs.csv,67141,67141,67141,67141,67141
karrierewege_plus_cp_val_pairs.csv,15102,15102,15102,15102,15102
karrierewege_plus_occ_test_pairs.csv,3428,3428,3428,3428,3428
karrierewege_plus_occ_train_pairs.csv,6130,6130,6130,6130,6130
karrierewege_plus_occ_val_pairs.csv,3466,3466,3466,3466,3466
talent_clef_pairs.csv,57760,0,57760,57760,57760

In [19]:
# for each dataframe in title_pairs, map pool with conceptUri column
for key in title_pairs.keys():
    title_pairs[key] = title_pairs[key].merge(pool, left_on='esco_id', right_on='conceptUri', how='left')

In [20]:
title_pairs['karrierewege_plus_cp_test_pairs.csv'].head()

,raw_title,esco_title,esco_id,conceptType,conceptUri,iscoGroup,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,regulatedProfessionNote,scopeNote,definition,inScheme,description,code
0,Agricultural Production Associate,crop production worker,http://data.europa.eu/esco/occupation/c9191f7f...,Occupation,http://data.europa.eu/esco/occupation/c9191f7f...,9213,crop production worker,farm worker\nfarm hand\ngrowing worker\ncrop w...,NaN,released,2024-01-23T10:51:59.37Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Crop production workers carry out practical ac...,9213.1
1,Educator for Students with Disabilities,special educational needs teacher secondary sc...,http://data.europa.eu/esco/occupation/034cad59...,Occupation,http://data.europa.eu/esco/occupation/034cad59...,2352,special educational needs teacher secondary sc...,teacher in special educational needs in second...,NaN,released,2024-01-12T13:41:37.173Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Special educational needs teachers at secondar...,2352.1.6
2,Sawmill Worker,metal sawing machine operator,http://data.europa.eu/esco/occupation/3a8a7f87...,Occupation,http://data.europa.eu/esco/occupation/3a8a7f87...,7223,metal sawing machine operator,cut-off operative\nmetal cut-off saw operator\...,NaN,released,2024-01-23T14:46:35.986Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Metal sawing machine operators set up and oper...,7223.4.5
3,Top Executive,department manager,http://data.europa.eu/esco/occupation/94e0bedd...,Occupation,http://data.europa.eu/esco/occupation/94e0bedd...,1219,department manager,business unit coordinator\nunit manager\nunit ...,NaN,released,2024-01-22T11:53:48.922Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Department managers are responsible for the op...,1219.4
4,Product Assurance Specialist,quality engineering technician,http://data.europa.eu/esco/occupation/998a0bf4...,Occupation,http://data.europa.eu/esco/occupation/998a0bf4...,3119,quality engineering technician,quality technologist\nquality engineering tech...,NaN,released,2023-06-01T10:47:06.518Z,http://data.europa.eu/esco/regulated-professio...,Excludes people performing the evaluation of t...,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Quality engineering technicians work with qual...,3119.16